### ISSUE TITLE
Translate to Swe

### ISSUE THREAD

**Issue by Maxainen** [NewGameSweden/newgamese#40]

**Comment by Criticalstone** [comment]
Probably fixed in 871ace58dbb623be2d5d3b723005e513d0034ddb, @Maxainen, @raxxor95 and @Mupperry: please check [dev.newgame.se](https://dev.newgame.se) to see if there are any left

**Comment by Maxainen** [comment]
![image](https://cloud.githubusercontent.com/assets/17413466/15138476/698c658e-1690-11e6-8766-eb1b5ba6adca.png)

**Comment by Maxainen** [comment]
Change from "Registrera" to "Bli medlem" and make it into a button.
